hirom

; ###############################################
; Synchysi's ASM

incsrc abort.asm
incsrc assassin_a-z_rage.asm
incsrc atb_start.asm
incsrc atma.asm
incsrc blind.asm
incsrc blitz.asm
incsrc blitz_menu.asm
incsrc bnw_blind_jump_fix.asm
incsrc bnw_config_remove_battle_speed.asm
incsrc bnw_equip_fix.asm
incsrc bnw_skills_window_remove.asm
incsrc break_usME.asm
incsrc bushido.asm
incsrc coin_toss.asm
incsrc combat_odds.asm
incsrc command_delays.asm
incsrc counterattacks.asm
incsrc cursed_shield.asm
incsrc dash.asm
incsrc dies_like_a_boss.asm
incsrc dn_aura_cycling.asm
incsrc dn_quarterstaff_fix.asm
incsrc dn_shop_hack.asm
incsrc dn_spell_dot.asm
incsrc dn_status_text.asm
incsrc dn_stop_block.asm
incsrc engulf.asm
incsrc esper_changes.asm
incsrc evade.asm
incsrc events.asm
incsrc exp_cap.asm
incsrc fig_EsperDetailsTweaks.asm
incsrc fig_SummonDescriptions.asm
incsrc fig_SynchysiTweaks.asm
incsrc gau_status_think.asm
incsrc gauntlet.asm
incsrc genji_menu_fix.asm
incsrc golem.asm
incsrc gray_battlemenu.asm
incsrc grayshadows_recoverretarget.asm
incsrc grayshadows_selswap.asm
incsrc heal_rod.asm
incsrc imp.asm
incsrc interceptor.asm
incsrc item_menu_fixes.asm
incsrc leap_anywhere.asm
incsrc madsiur_aero.asm
incsrc magic_condensing.asm
incsrc magic_defend.asm
incsrc master_thief.asm
incsrc miss_status_strip.asm
incsrc mog_stuff.asm
incsrc morph.asm
incsrc mp_for_crit.asm
incsrc music.asm
incsrc mystery-egg.asm
incsrc natb.asm
incsrc no_exp_option.asm
incsrc no_moogle_suit.asm
incsrc optimize.asm
incsrc periodic_effects.asm
incsrc phys_dmg_calc.asm
incsrc rage.asm
incsrc random_cast.asm
incsrc random_variance.asm
incsrc respec.asm
incsrc restrict_espers.asm
incsrc rewards_display.asm
incsrc rng_update.asm
incsrc rod_fix.asm
incsrc roulette.asm
incsrc runic.asm
incsrc ryo_shop.asm
incsrc scan.asm
incsrc sei_atb_colors.asm
incsrc sei_encounter_rate.asm
incsrc sei_golem.asm
incsrc sei_item_id_fix.asm
incsrc sei_lifehack.asm
incsrc sei_melee_counter.asm
incsrc sei_mp_fix.asm
incsrc sei_mp_low_counter.asm
incsrc sei_narshe.asm
incsrc sei_quicksteal.asm
incsrc sei_reflect_timer.asm
incsrc sei_repo_hacks.asm
incsrc sei_srbehemoth.asm
incsrc sei_stamcounter.asm
incsrc sei_tank_n_spank.asm
incsrc set_level.asm
incsrc shock.asm
incsrc sketch_fix.asm
incsrc slots.asm
incsrc speed.asm
incsrc stamina.asm
incsrc stone.asm
incsrc text.asm
incsrc think.asm
incsrc think_esper_junction.asm
incsrc throw.asm
incsrc tintinabar_effect.asm
incsrc tools.asm
incsrc umaro_fixes.asm
incsrc vanish_doom.asm
incsrc wor_music.asm
incsrc wpn_effects.asm
incsrc x-magic_counter.asm
incsrc zantetsuken.asm
